### ISSUE TITLE
[feature request] echoing Access-Control-Request-Headers to Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by vladimirgamalyan** [itsjamie/gin-cors#7]
It will be convinient if git-cors has ability to fill a response header "Access-Control-Allow-Headers" with content of a request header "Access-Control-Request-Headers".

**Comment by itsjamie** [comment]
What is this the intended use-case?

If it is to make development easier, how about adding a development flag which allows everything and logs the headers set via the log package?

**Comment by vladimirgamalian** [comment]
Sorry for the late answer. Yes, the primary use-case is to make development more comfortable. The flag would be a good solution.

**Comment by itsjamie** [comment]
I'm open to a PR for this. Just don't have the time to do it myself.

**Comment by itsjamie** [comment]
Due to the lack of anyone interested in picking this up. I'm going to close.
