### ISSUE TITLE
[GIN-debug] redirecting request 307 

### ISSUE THREAD

**Issue by almgwary** [itsjamie/gin-cors#9]
i didn't found any answer for this issue .
I am trying to call simple API, but it `redirecting request 307` . and the request fail on client side .
as you see in the first screen shot there is 3 requests . first one is option with `Status Code:200 OK` .
the next 2 requests with `Status Code:307 Temporary Redirect`
port 3030 is server
port 8100 is client 
CORS middleware is [gin-cors](https://github.com/itsjamie/gin-cors)

![image](https://user-images.githubusercontent.com/7817756/28049448-c65bc4be-65f7-11e7-8711-c2f6f7ac00a0.png)

![image](https://user-images.githubusercontent.com/7817756/28049470-ec6c8db4-65f7-11e7-9d94-40801228bed6.png)

![image](https://user-images.githubusercontent.com/7817756/28049481-f928298c-65f7-11e7-9029-95a1d59b79fa.png)

and this is the code 
```go
// Creates a gin router with default middleware:
	router := gin.Default()
	// Apply the middleware to the router (works with groups too)
	router.Use(cors.Middleware(cors.Config{
		Origins:        "*",
		Methods:        "GET, PUT, POST, DELETE",
		RequestHeaders: "Origin, Authorization, Content-Type",
		ExposedHeaders: "",
		MaxAge: 300 * time.Second,
		Credentials: false,
		ValidateHeaders: false,
	}))

       router.POST("/api/v1/login", usersController.Login)
```
client side error 
```
XMLHttpRequest cannot load http://localhost:3030/api/v1/login/. Redirect from
 'http://localhost:3030/api/v1/login/' to 'http://localhost:3030/api/v1/login' has been blocked by CORS 
policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 
'http://localhost:8100' is therefore not allowed access.

```

it works fine on postman

**Comment by itsjamie** [comment]
I think you must have Credentials set to true.

If you look at the headers returned on your first response, it's setting the allowed origin to localhost:8100.

If you are using `Origins: *` and `Credentials: false`, then you shouldn't see it return the `Access-Control-Allow-Origin: http://localhost:8100`.

The related code is this:

```go
if valid {
	if config.Credentials {
		context.Writer.Header().Set(AllowCredentialsKey, config.credentials)
		// Allowed origins cannot be the string "*" cannot be used for a resource that supports credentials.
		context.Writer.Header().Set(AllowOriginKey, currentOrigin)
	} else if forceOriginMatch {
		context.Writer.Header().Set(AllowOriginKey, "*")
	} else {
		context.Writer.Header().Set(AllowOriginKey, currentOrigin)
	}

	//If this is a preflight request, we are finished, quit.
	//Otherwise this is a normal request and operations should proceed at normal
	if preflight {
		context.AbortWithStatus(200)
	}
	return
}
```

**Comment by almgwary** [comment]
i changed the  `Origins` to ` http://localhost:8100`  and `Credentials` to `false` .
but still i have the same issue 
```

	router.Use(cors.Middleware(cors.Config{
		Origins:         "http://localhost:8100",
		Methods:         "GET, PUT, POST, DELETE",
		RequestHeaders:  "Origin, Authorization, Content-Type",
		ExposedHeaders:  "",
		MaxAge:          300 * time.Second,
		Credentials:     true,
		ValidateHeaders: false,
	}))
```

**Comment by almgwary** [comment]
I think problem is client side, because it works fine with another client side app .
issue not related to `gin-cors`  . 
Thanks

![image](https://user-images.githubusercontent.com/7817756/28070994-07151f94-664f-11e7-92e1-c7c55fb8c005.png)

**Comment by almgwary** [comment]
@itsjamie @tuvistavie 

SOLVED

problem was with URL 

- `...url/login ` **Passed** 
- `...url/login/ ` **Failed** because of extra `/`

**Comment by yektayazdani** [comment]
Hi @almgwary ,
I know its ages past this issue. but what client were you using at that point of time?
I am facing the same issue with Angular 4 and not able to fix it. tried removing / and all other sort of things.
Thanks.
